config/routes.rb
Rails.application.routes.draw do
  resources :artists, only: [:index, :show]
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums, dependent: :destroy
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Real Music</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Artistas <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Mi música</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Mi cuenta </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Login in</a>
                <a class="dropdown-item" href="#">Logout</a>
                <a class="dropdown-item" href="#">Sign up</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <% @artists.each do |artist| %>
      <div class="col-3 m-4 p-3">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="<%= artist.image_url %>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title text-center"><%= artist.name %></h5>
            <%= link_to "Ver más", artist_path(artist.id), class: "btn btn-primary btn-lg btn-block" %>
          </div>
        </div>
      </div>
    <% end %>  
  </div>  
</div>

app/views/artists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Real Music</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Artistas <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Mi música</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Mi cuenta </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Login in</a>
                <a class="dropdown-item" href="#">Logout</a>
                <a class="dropdown-item" href="#">Sign up</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-8">
      <h2><%= @artist.name %></h2>
      <h3> Albums (<%= @artist.albums.count %>)</h3>
      <div class="row m-2">
        <% @artist.albums.each do |album| %>
          <div class="col-4 m-2">
            <div class="card" style="width: 15rem;">
              <img class="card-img-top" src="<%= album.image_url %>" alt="Card image cap">
              <div class="card-body">
                <h5 class="card-title text-left" style="font-size: 15px;"><%= album.name %></h5>
                <h5 class="card-title text-left" style="font-size: 15px;"><%= l album.released_at, format: '%Y' if album.released_at %></h5>
              </div>
            </div>
          </div>
        <% end %>  
      </div>  
    </div>
    <div class="col-2 m-3">
      <img class="card" style="width: 20rem;" src="<%= @artist.image_url %>">
    </div>  
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppMusic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body class="p-3 bg-light">
    <%= yield %>
  </body>
</html>